### ISSUE TITLE
group and heating element gaskets

### ISSUE THREAD

**Issue by tsuresuregusa** [derekmccallum/gaggia-220-boiler-gasket-template#1]
Hi Derek

I just got myself a gaggia orione and need to replace all the gaskets. I have a cnc at work so was thinking to cut them from PTFE. Do you maybe have the templates for the other parts? if not I'll can send them to you when I make them. Also, I saw somewhere that for the boiler gasket they sell a 3mm seal... you think 2mm is thick enough for all the seals? 

thanks for your work!
Sebastian

**Comment by derekmccallum** [comment]
Hi Sebastian,
I created this pattern for a Gaggia Internazionale I was restoring, but I didn't do the heating element gasket as I'd ordered some from a supplier. Give me a day or two and I'll measure one up.
Feel free to pass designs you create over and I will publish them here.

Wrt to the thickness, for a boiler, grouphead or similar I found 2mm was sufficient. 

Regards,
Derek

**Comment by derekmccallum** [comment]
Hi Sebastian,
Triangular 3-hole element provided at https://github.com/derekmccallum/GAGGIA-boiler-element-gasket-template.

Regards,
Derek

**Comment by tsuresuregusa** [comment]
Thanks a lot Derek, have been busy at work this week, I'll let you know how
it goes with the restoration :)

**Comment by derekmccallum** [comment]
You're welcome.
